---
- name: Install required packages
  package:
    update_cache: yes
    name:
      - sshfs

- name: Upload SSH key
  copy:
    content: "{{ priv_key_b64 | b64decode }}"
    dest: /home/ubuntu/.ssh/id_rsa
    owner: ubuntu
    group: ubuntu
    mode: 0600

- name: enable user_allow_other in fuse config
  lineinfile:
    path: /etc/fuse.conf
    regexp: '^#user_allow_other$'
    line: 'user_allow_other'
    state: present

# Do not show warnings about unknown SSH keys
- name: add ip_fileserver to know_hosts 
  shell: "ssh-keyscan {{ ip_fileserver }}>> ~/.ssh/known_hosts"

- name: Ensure /usr/local/bin/ dir exists
  file:
    path: /usr/local/bin/
    state: directory
    mode: 0777

- name: Create script for pam
  copy:
    src: sshfs_mount.sh
    dest: /usr/local/bin/sshfs_mount.sh
    mode: 0777

- name: Edit sshfs_mount.sh to set the correct server url
  lineinfile:
    path: /usr/local/bin/sshfs_mount.sh
    regexp: '^FILESERVER_URL='
    line: "FILESERVER_URL={{ ip_fileserver }}"

- name: Edit sshfs_mount.sh to set the correct remote volume name
  lineinfile:
    path: /usr/local/bin/sshfs_mount.sh
    regexp: '^REMOTE_VOLUME='
    line: "REMOTE_VOLUME=volume_2"

- name: Create pam entry for mounting sshfs
  register: pam_sshfs
  copy:
    dest: /usr/share/pam-configs/sshfs
    mode: 0644
    src: pam-configs/sshfs

- name: Update pam for sshfs
  when: pam_sshfs is changed
  command: pam-auth-update --package sshfs
