- hosts: 127.0.0.1
  connection: local
  become: yes
  gather_facts: no

  tasks:
    - name: Create a directory if it does not exist
      file:
        path: HU
        state: directory
        mode: '0755'

    - name: add file
      file:
        path: HU/test.txt
        state: touch
        mode: '0755'
    
    - name: install packages
      apt:
        name: 
          - python3
          - python3-pip
          - git

    - name: clone the repo
      git:
        repo: https://github.com/uashogeschoolutrecht/ResearcherScraper
        dest: repo

    - name: install requirements in virtualenv
      pip:
        requirements: /repo/requirements.txt
        virtualenv: /repo/venv

    - name: run the python script
      shell: /repo/venv/bin/python3 /repo/scrape.py
