- hosts: 127.0.0.1
  connection: local
  become_user: ubuntu
  gather_facts: no
  roles:

  vars_files:
    - ./group_vars/dataiku

  tasks:
    - name: Install vscode
      apt:
        deb:  https://github.com/coder/code-server/releases/download/v4.6.0/code-server_4.6.0_amd64.deb

    - name: Start vscode with systemd
      systemd:
        name: code-server
        enabled: yes
        state: started

    - name: copy nginx config
      copy:
        src: ../files/vscode/nginx.conf
        dest: /etc/nginx/app-location-conf.d/vscode.conf
      notify: restart nginx
      
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted