- hosts: 127.0.0.1
  connection: local
  become_user: ubuntu
  gather_facts: no
  roles:
    - python3.6-base
  vars_files:
    - ./group_vars/dataiku

  tasks:
    - name: install code server
      become: false
      shell: curl -fsSL https://code-server.dev/install.sh | sh

  #   - name: copy nginx config
  #     copy:
  #       src: ../files/dataiku/nginx.conf
  #       dest: /etc/nginx/app-location-conf.d/rstudio.conf
  #     notify: restart nginx

  # handlers:
  #   - name: restart nginx
  #     service:
  #       name: nginx
  #       state: restarted